global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "haproxy"
    static_configs:
      - targets: ["haproxy-exporter:9101"]

  - job_name: "mms-api"
    static_configs:
      - targets: ["mms-api:8000"]

  - job_name: "mock-carriers"
    static_configs:
      - targets: ["tmobile-sdg1:8080", "tmobile-sdg2:8080"]

  - job_name: "mms-workers"
    static_configs:
      - targets: ["worker-tmobile-egress:9102"]
